"""
Expert Filter Module
Restores tag-based expert routing - core Mycelium philosophy

This module ensures that only relevant experts are evaluated for each input,
based on the tags generated by Layer 1. This prevents the system from forcing
inputs into wrong domains and enables proper detection of missing experts.

Uses automatic semantic clustering to eliminate manual dictionary maintenance.
"""

from auto_semantic_clusterer import AutoSemanticClusterer

class ExpertFilter:
    """
    Filters experts based on input tags to ensure only relevant
    experts are evaluated for each input.
    
    Uses semantic embeddings for automatic tag clustering - no manual
    dictionary maintenance required!
    """
    
    def __init__(self, domain_list=None, use_auto_clustering=True, similarity_threshold=0.45):
        """
        Initialize expert filter.
        
        Args:
            domain_list: List of all defined domains (for compatibility)
            use_auto_clustering: Whether to use automatic semantic clustering
            similarity_threshold: Minimum similarity for auto-clustering (0.0-1.0)
        """
        raw_domain_list = domain_list or [
            "AI", "healthcare", "logistics", "finance", "education", 
            "physics", "maths", "biology", "chemistry", "technology", 
            "sports", "politics", "history", "art", "music", "literature"
        ]
        
        # Bug 3 (coverage_stats key-case fix): store domain names in lowercase
        # so that coverage_stats lookups are case-insensitive.  Previously
        # 'AI' (capitals) was stored as-is, but AutoSemanticClusterer returns
        # its anchor keys in lowercase, so normalize_domain('AI') returned
        # 'AI' but the coverage_stats lookup missed it.
        self.domain_list = raw_domain_list
        self.use_auto_clustering = use_auto_clustering
        self.similarity_threshold = similarity_threshold
        
        if self.use_auto_clustering:
            print("🔧 Initializing automatic semantic tag clustering...")
            self.clusterer = AutoSemanticClusterer()
            self.clusterer.similarity_threshold = self.similarity_threshold
            self.clusterer.initialize()
            print("✅ Auto-clustering ready")
        else:
            self.semantic_clusters = {
                'medical': ['medical', 'medicine', 'healthcare', 'health', 'biology', 
                           'bio', 'biological', 'biomedical', 'clinical', 'patient',
                           'disease', 'diagnosis', 'therapy', 'treatment'],
                'physics': ['physics', 'phys', 'quantum', 'mechanics', 'thermodynamics',
                           'optics', 'electromagnetism', 'particle'],
                'chemistry': ['chemistry', 'chem', 'chemical', 'molecule', 'compound',
                             'reaction', 'organic', 'inorganic', 'biochemistry'],
                'maths': ['maths', 'math', 'mathematics', 'mathematical', 'algebra',
                         'calculus', 'geometry', 'statistics'],
                'technology': ['technology', 'tech', 'engineering', 'software', 'hardware',
                              'computer', 'digital'],
                'music': ['music', 'musical', 'song', 'melody', 'instrument', 'audio'],
                'AI': ['AI', 'artificial intelligence', 'machine learning', 'ML', 'deep learning',
                      'neural network', 'NLP']
            }
            
            self.tag_to_domain = {}
            for domain, tags in self.semantic_clusters.items():
                for tag in tags:
                    self.tag_to_domain[tag.lower()] = domain
            
            self.ignore_tags = {'science', 'research', 'study', 'analysis', 'data'}
        
        # Use lowercase keys for coverage stats so case-insensitive lookups work.
        self.coverage_stats = {domain.lower(): 0 for domain in raw_domain_list}
    
    def normalize_domain(self, domain):
        """
        Normalize domain/tag name using semantic clustering.
        Maps semantically related tags to their canonical domain.
        """
        domain_lower = domain.lower().strip()
        
        if self.use_auto_clustering:
            canonical_domain, confidence = self.clusterer.cluster_tag(domain_lower)
            
            if canonical_domain and confidence >= self.similarity_threshold:
                return canonical_domain
            else:
                return None
        else:
            if domain_lower in self.ignore_tags:
                return None
            
            canonical = self.tag_to_domain.get(domain_lower)
            if canonical:
                return canonical
            
            return domain_lower
    
    def filter_experts_by_tags(self, tags, expert_system, bert_manager):
        """
        Filter experts to only those matching input tags.
        
        Args:
            tags: List of normalized tags from Layer 1
            expert_system: UnifiedExpertSystem instance (SVM experts)
            bert_manager: BERTExpertManager instance (BERT experts)
        
        Returns:
            Dictionary with:
            - relevant_svm_experts: List of SVM expert domains
            - relevant_bert_experts: List of BERT expert domains
            - missing_domains: List of tags with no expert
            - coverage_status: Coverage analysis
        """
        available_svm = set(expert_system.experts.keys()) if hasattr(expert_system, 'experts') else set()
        available_bert = set(bert_manager.get_available_domains()) if bert_manager else set()
        
        # Bug 3 fix: filter out None values from the normalized sets so that
        # low-confidence auto-cluster results don't pollute all_available and
        # silently suppress missing-expert detection.
        available_svm_normalized = {
            d for d in (self.normalize_domain(x) for x in available_svm) if d is not None
        }
        available_bert_normalized = {
            d for d in (self.normalize_domain(x) for x in available_bert) if d is not None
        }
        all_available = available_svm_normalized | available_bert_normalized
        
        relevant_svm = []
        relevant_bert = []
        missing_domains = []
        
        for tag in tags:
            normalized_tag = self.normalize_domain(tag)
            
            # Coverage stats use lowercase keys (see __init__).
            stats_key = normalized_tag.lower() if normalized_tag else tag.lower()
            if stats_key in self.coverage_stats:
                self.coverage_stats[stats_key] += 1
            
            if normalized_tag is not None and normalized_tag in available_svm_normalized:
                for domain in expert_system.experts.keys():
                    if self.normalize_domain(domain) == normalized_tag:
                        relevant_svm.append(domain)
                        break
            
            if normalized_tag is not None and normalized_tag in available_bert_normalized:
                for domain in bert_manager.get_available_domains():
                    if self.normalize_domain(domain) == normalized_tag:
                        relevant_bert.append(domain)
                        break
            
            if normalized_tag is None or normalized_tag not in all_available:
                missing_domains.append(tag)
        
        relevant_svm = list(dict.fromkeys(relevant_svm))
        relevant_bert = list(dict.fromkeys(relevant_bert))
        
        return {
            'relevant_svm_experts': relevant_svm,
            'relevant_bert_experts': relevant_bert,
            'missing_domains': missing_domains,
            'has_expert_coverage': len(relevant_svm) > 0 or len(relevant_bert) > 0,
            'available_svm': list(available_svm),
            'available_bert': list(available_bert),
            'input_tags': tags
        }
    
    def add_domain(self, domain_name, anchor_terms):
        """
        Dynamically add a new domain to the clustering system.
        """
        if not self.use_auto_clustering:
            print(f"⚠️ Cannot add domain dynamically - auto-clustering is disabled")
            return False
        
        self.clusterer.domain_anchors[domain_name] = anchor_terms
        self.clusterer._compute_domain_embeddings()
        self.clusterer.save_cache()
        
        print(f"✅ Added new domain: {domain_name} with {len(anchor_terms)} anchor terms")
        return True
    
    def analyze_coverage_gaps(self):
        """
        Analyze which domains have samples but no experts.
        """
        domains_with_samples = {d: count for d, count in self.coverage_stats.items() if count > 0}
        
        return {
            'total_domains_defined': len(self.domain_list),
            'domains_with_samples': len(domains_with_samples),
            'domain_sample_counts': domains_with_samples,
            'domains_needing_experts': [d for d in domains_with_samples.keys()]
        }
    
    def should_create_new_expert(self, filter_result):
        """
        Determine if new expert creation is needed.
        """
        return (
            len(filter_result['missing_domains']) > 0 and
            not filter_result['has_expert_coverage']
        )
    
    def get_coverage_report(self, registered_expert_domains=None):
        """
        Generate comprehensive coverage report.

        Args:
            registered_expert_domains: Optional set/list of domain names that
                have a live expert in the system.  When provided, the report
                classifies a domain as "supported" if and only if it appears
                in this collection.  Falls back to the original hard-coded
                allowlist only when the argument is omitted.
        """
        coverage_gaps = self.analyze_coverage_gaps()
        domains_with_samples = coverage_gaps['domain_sample_counts']

        # Bug 2 fix: use the live expert registry instead of a hardcoded
        # domain allowlist so every registered expert is treated as supported.
        if registered_expert_domains is not None:
            supported_set = {d.lower() for d in registered_expert_domains}
        else:
            supported_set = {'healthcare', 'medical', 'physics', 'chemistry'}
        
        supported_domains = {}
        unsupported_domains = {}
        
        for domain, count in domains_with_samples.items():
            if domain.lower() in supported_set:
                supported_domains[domain] = count
            else:
                unsupported_domains[domain] = count
        
        total_samples = sum(domains_with_samples.values())
        unsupported_samples = sum(unsupported_domains.values())
        
        return {
            'summary': {
                'total_domains_defined': coverage_gaps['total_domains_defined'],
                'domains_with_samples': coverage_gaps['domains_with_samples'],
                'supported_domains_count': len(supported_domains),
                'unsupported_domains_count': len(unsupported_domains),
                'total_samples_seen': total_samples,
                'samples_needing_new_experts': unsupported_samples,
                'coverage_percentage': (len(supported_domains) / len(domains_with_samples) * 100) if domains_with_samples else 0
            },
            'supported_domains': supported_domains,
            'unsupported_domains': unsupported_domains,
            'all_domains_with_samples': domains_with_samples
        }
