"""
Expert Filter Module
Restores tag-based expert routing - core Mycelium philosophy

This module ensures that only relevant experts are evaluated for each input,
based on the tags generated by Layer 1. This prevents the system from forcing
inputs into wrong domains and enables proper detection of missing experts.
"""

class ExpertFilter:
    """
    Filters experts based on input tags to ensure only relevant
    experts are evaluated for each input.
    """
    
    def __init__(self, domain_list=None):
        """
        Initialize expert filter.
        
        Args:
            domain_list: List of all defined domains
        """
        self.domain_list = domain_list or [
            "AI", "healthcare", "logistics", "finance", "education", 
            "physics", "maths", "biology", "chemistry", "technology", 
            "sports", "politics", "history", "art", "music", "literature"
        ]
        
        # Domain aliases for flexible matching
        self.domain_aliases = {
            'medicine': 'medical',
            'healthcare': 'medical',
            'math': 'maths',
            'mathematics': 'maths',
            'chem': 'chemistry',
            'phys': 'physics',
            'bio': 'biology',
            'tech': 'technology',
            'lit': 'literature',
            'science': None  # Generic tag, ignore for expert matching
        }
        
        # Track coverage
        self.coverage_stats = {domain: 0 for domain in self.domain_list}
    
    def normalize_domain(self, domain):
        """Normalize domain name using aliases."""
        domain_lower = domain.lower()
        normalized = self.domain_aliases.get(domain_lower, domain_lower)
        # Skip generic tags that map to None
        return normalized if normalized is not None else domain_lower
    
    def filter_experts_by_tags(self, tags, expert_system, bert_manager):
        """
        Filter experts to only those matching input tags.
        
        Args:
            tags: List of normalized tags from Layer 1
            expert_system: UnifiedExpertSystem instance (SVM experts)
            bert_manager: BERTExpertManager instance (BERT experts)
        
        Returns:
            Dictionary with:
            - relevant_svm_experts: List of SVM expert domains
            - relevant_bert_experts: List of BERT expert domains
            - missing_domains: List of tags with no expert
            - coverage_status: Coverage analysis
        """
        # Get available expert domains
        available_svm = set(expert_system.experts.keys()) if hasattr(expert_system, 'experts') else set()
        available_bert = set(bert_manager.get_available_domains()) if bert_manager else set()
        
        # Normalize available domains
        available_svm_normalized = {self.normalize_domain(d) for d in available_svm}
        available_bert_normalized = {self.normalize_domain(d) for d in available_bert}
        all_available = available_svm_normalized | available_bert_normalized
        
        # Check each tag
        relevant_svm = []
        relevant_bert = []
        missing_domains = []
        
        for tag in tags:
            normalized_tag = self.normalize_domain(tag)
            
            # Update coverage stats
            if normalized_tag in self.coverage_stats:
                self.coverage_stats[normalized_tag] += 1
            
            # Check if expert exists
            if normalized_tag in available_svm_normalized:
                # Find original domain name
                for domain in expert_system.experts.keys():
                    if self.normalize_domain(domain) == normalized_tag:
                        relevant_svm.append(domain)
                        break
            
            if normalized_tag in available_bert_normalized:
                for domain in bert_manager.get_available_domains():
                    if self.normalize_domain(domain) == normalized_tag:
                        relevant_bert.append(domain)
                        break
            
            if normalized_tag not in all_available:
                missing_domains.append(tag)
        
        # Remove duplicates while preserving order
        relevant_svm = list(dict.fromkeys(relevant_svm))
        relevant_bert = list(dict.fromkeys(relevant_bert))
        
        return {
            'relevant_svm_experts': relevant_svm,
            'relevant_bert_experts': relevant_bert,
            'missing_domains': missing_domains,
            'has_expert_coverage': len(relevant_svm) > 0 or len(relevant_bert) > 0,
            'available_svm': list(available_svm),
            'available_bert': list(available_bert),
            'input_tags': tags
        }
    
    def analyze_coverage_gaps(self):
        """
        Analyze which domains have samples but no experts.
        
        Returns:
            Dictionary with coverage analysis
        """
        domains_with_samples = {d: count for d, count in self.coverage_stats.items() if count > 0}
        
        return {
            'total_domains_defined': len(self.domain_list),
            'domains_with_samples': len(domains_with_samples),
            'domain_sample_counts': domains_with_samples,
            'domains_needing_experts': [d for d in domains_with_samples.keys()]
        }
    
    def should_create_new_expert(self, filter_result):
        """
        Determine if new expert creation is needed.
        
        Args:
            filter_result: Result from filter_experts_by_tags
        
        Returns:
            Boolean indicating if create_new_expert flag should be raised
        """
        return (
            len(filter_result['missing_domains']) > 0 and
            not filter_result['has_expert_coverage']
        )
    
    def get_coverage_report(self):
        """
        Generate comprehensive coverage report.
        
        Returns:
            Dictionary with detailed coverage statistics
        """
        coverage_gaps = self.analyze_coverage_gaps()
        domains_with_samples = coverage_gaps['domain_sample_counts']
        
        # Categorize domains
        supported_domains = {}
        unsupported_domains = {}
        
        for domain, count in domains_with_samples.items():
            # This is a simplified check - should be enhanced with actual expert availability
            if domain.lower() in ['healthcare', 'medical', 'physics', 'chemistry']:
                supported_domains[domain] = count
            else:
                unsupported_domains[domain] = count
        
        total_samples = sum(domains_with_samples.values())
        unsupported_samples = sum(unsupported_domains.values())
        
        return {
            'summary': {
                'total_domains_defined': coverage_gaps['total_domains_defined'],
                'domains_with_samples': coverage_gaps['domains_with_samples'],
                'supported_domains_count': len(supported_domains),
                'unsupported_domains_count': len(unsupported_domains),
                'total_samples_seen': total_samples,
                'samples_needing_new_experts': unsupported_samples,
                'coverage_percentage': (len(supported_domains) / len(domains_with_samples) * 100) if domains_with_samples else 0
            },
            'supported_domains': supported_domains,
            'unsupported_domains': unsupported_domains,
            'all_domains_with_samples': domains_with_samples
        }
