"""
Expert Filter Module
Restores tag-based expert routing - core Mycelium philosophy

This module ensures that only relevant experts are evaluated for each input,
based on the tags generated by Layer 1. This prevents the system from forcing
inputs into wrong domains and enables proper detection of missing experts.

Uses automatic semantic clustering to eliminate manual dictionary maintenance.

Stage 4 (transparency emitter): ExpertFilter now accepts an optional
``on_event`` callback (same signature as the one threaded through
run_mycelium_workflow).  Two structured PipelineEvents are emitted:

  graph_expert_init       — fired at the end of __init__ once the clusterer /
                            fallback dictionaries are ready.  Reports domain
                            count, clustering mode, and similarity threshold.

  graph_coverage_report   — fired at the end of filter_experts_by_tags once
                            available/missing domain sets are resolved.
                            visibility=internal so it never surfaces in the
                            public SSE stream.
"""

from functools import lru_cache
from typing import Any, Callable, Dict, Iterable, Optional
from mycelium.pipeline.auto_semantic_clusterer import AutoSemanticClusterer


class ExpertFilter:
    """
    Filters experts based on input tags to ensure only relevant
    experts are evaluated for each input.

    Uses semantic embeddings for automatic tag clustering - no manual
    dictionary maintenance required!
    """

    def __init__(
        self,
        domain_list=None,
        use_auto_clustering=True,
        similarity_threshold=0.45,
        on_event: Optional[Callable[[Dict[str, Any]], None]] = None,
    ):
        """
        Initialize expert filter.

        Args:
            domain_list:          List of all defined domains (for compatibility)
            use_auto_clustering:  Whether to use automatic semantic clustering
            similarity_threshold: Minimum similarity for auto-clustering (0.0-1.0)
            on_event:             Optional PipelineEvent callback supplied by
                                  run_mycelium_workflow.  When provided a
                                  ``graph_expert_init`` event is emitted once
                                  the clusterer is ready.  The callback MUST
                                  never raise; exceptions are silently swallowed
                                  so they cannot abort initialisation.
        """
        raw_domain_list = domain_list or [
            "AI", "healthcare", "logistics", "finance", "education",
            "physics", "maths", "biology", "chemistry", "technology",
            "sports", "politics", "history", "art", "music", "literature"
        ]

        self.domain_list = raw_domain_list
        self.use_auto_clustering = use_auto_clustering
        self.similarity_threshold = similarity_threshold
        self._on_event = on_event

        # Frozen set of all registered domain names (lower-cased) for O(1)
        # membership tests inside the per-sentence routing loop (§3.1).
        self._domain_set: frozenset = frozenset(d.lower() for d in raw_domain_list)

        if self.use_auto_clustering:
            print("\U0001f527 Initializing automatic semantic tag clustering...")
            self.clusterer = AutoSemanticClusterer()
            self.clusterer.similarity_threshold = self.similarity_threshold
            self.clusterer.initialize()
            print("\u2705 Auto-clustering ready")
        else:
            self.semantic_clusters = {
                'medical': ['medical', 'medicine', 'healthcare', 'health', 'biology',
                            'bio', 'biological', 'biomedical', 'clinical', 'patient',
                            'disease', 'diagnosis', 'therapy', 'treatment'],
                'physics': ['physics', 'phys', 'quantum', 'mechanics', 'thermodynamics',
                            'optics', 'electromagnetism', 'particle'],
                'chemistry': ['chemistry', 'chem', 'chemical', 'molecule', 'compound',
                              'reaction', 'organic', 'inorganic', 'biochemistry'],
                'maths': ['maths', 'math', 'mathematics', 'mathematical', 'algebra',
                          'calculus', 'geometry', 'statistics'],
                'technology': ['technology', 'tech', 'engineering', 'software', 'hardware',
                               'computer', 'digital'],
                'music': ['music', 'musical', 'song', 'melody', 'instrument', 'audio'],
                'AI': ['AI', 'artificial intelligence', 'machine learning', 'ML', 'deep learning',
                       'neural network', 'NLP']
            }

            self.tag_to_domain = {}
            for domain, tags in self.semantic_clusters.items():
                for tag in tags:
                    self.tag_to_domain[tag.lower()] = domain

            self.ignore_tags = {'science', 'research', 'study', 'analysis', 'data'}

        # Use lowercase keys for coverage stats so case-insensitive lookups work.
        self.coverage_stats = {domain.lower(): 0 for domain in raw_domain_list}

        # ── graph_expert_init event ───────────────────────────────────────────
        # Emitted once after the clusterer / fallback dictionaries are ready.
        # visibility=public: safe to surface in the frontend phase timeline.
        self._emit(
            phase_name="graph_expert_init",
            phase_id=2,
            substep="init",
            state="done",
            visibility="public",
            message="Expert system initialised",
            detail=(
                f"{len(raw_domain_list)} domains · "
                f"{'auto-clustering' if use_auto_clustering else 'static-clusters'} · "
                f"threshold={similarity_threshold}"
            ),
            metadata={
                "domain_count": len(raw_domain_list),
                "use_auto_clustering": use_auto_clustering,
                "similarity_threshold": similarity_threshold,
            },
        )

    # ── Internal event helper ─────────────────────────────────────────────────

    def _emit(
        self,
        phase_name: str,
        phase_id: int,
        substep: str,
        state: str,
        visibility: str,
        message: str,
        detail: str = "",
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Fire a PipelineEvent dict through ``_on_event`` if registered.

        Exceptions from the callback are caught and silently discarded so that
        a broken telemetry path can never abort the core reasoning pipeline.
        """
        if self._on_event is None:
            return
        try:
            from pipeline_event import build_event
            ev = build_event(
                phase_name=phase_name,
                phase_id=phase_id,
                substep=substep,
                state=state,
                visibility=visibility,
                message=message,
                detail=detail,
                metadata=metadata or {},
            )
            self._on_event(ev)
        except Exception:
            pass  # telemetry must never crash the pipeline

    # ── Public API ────────────────────────────────────────────────────────────

    def normalize_domain(self, domain):
        """
        Normalize domain/tag name using semantic clustering.
        Maps semantically related tags to their canonical domain.

        Per-instance LRU cache (§3.1): pure function of domain string for a
        fixed clusterer / tag_to_domain mapping.  512 entries covers any
        realistic vocabulary of domain names and input tags.
        """
        return self._normalize_domain_cached(domain)

    @lru_cache(maxsize=512)
    def _normalize_domain_cached(self, domain: str) -> Optional[str]:
        """LRU-cached implementation of normalize_domain (§3.1)."""
        domain_lower = domain.lower().strip()

        if self.use_auto_clustering:
            canonical_domain, confidence = self.clusterer.cluster_tag(domain_lower)

            if canonical_domain and confidence >= self.similarity_threshold:
                return canonical_domain
            else:
                return None
        else:
            if domain_lower in self.ignore_tags:
                return None

            canonical = self.tag_to_domain.get(domain_lower)
            if canonical:
                return canonical

            return domain_lower

    def filter_experts_by_tags(
        self,
        tags,
        expert_system,
        bert_manager=None,
        bert_domains: Optional[Iterable[str]] = None,
    ):
        """
        Filter experts to only those matching input tags.

        Args:
            tags:         List of normalized tags from Layer 1
            expert_system: UnifiedExpertSystem instance (SVM experts)
            bert_manager:  BERTExpertManager instance (BERT experts), or None
            bert_domains:  Optional explicit list of BERT-backed domain names.
                           When bert_manager is None this is the only source of
                           BERT domain information.  Pass
                           expert_system.experts.keys() (or a superset) when
                           calling from a context that has no live
                           BERTExpertManager but still wants BERT domains
                           counted as available so they are not falsely reported
                           as missing.  (Trip 3 fix)

        Returns:
            Dictionary with:
            - relevant_svm_experts: List of SVM expert domains
            - relevant_bert_experts: List of BERT expert domains
            - missing_domains: List of tags with no expert
            - coverage_status: Coverage analysis
        """
        available_svm = set(expert_system.experts.keys()) if hasattr(expert_system, 'experts') else set()

        # Trip 3 fix: when bert_manager is None, fall back to the explicit
        # bert_domains iterable (if provided) so that BERT-backed domains are
        # not incorrectly reported as missing just because no live manager
        # was supplied.  This is the common case in the fallback pre-check
        # path in run_workflow.py.
        if bert_manager is not None:
            available_bert = set(bert_manager.get_available_domains())
        elif bert_domains is not None:
            available_bert = set(bert_domains)
        else:
            available_bert = set()

        # Filter out None values so low-confidence auto-cluster results
        # don't pollute all_available and silently suppress missing-expert
        # detection (Bug 3 / original fix preserved).
        available_svm_normalized = {
            d for d in (self.normalize_domain(x) for x in available_svm) if d is not None
        }
        available_bert_normalized = {
            d for d in (self.normalize_domain(x) for x in available_bert) if d is not None
        }
        all_available = available_svm_normalized | available_bert_normalized

        relevant_svm = []
        relevant_bert = []
        missing_domains = []

        for tag in tags:
            normalized_tag = self.normalize_domain(tag)

            stats_key = normalized_tag.lower() if normalized_tag else tag.lower()
            if stats_key in self.coverage_stats:
                self.coverage_stats[stats_key] += 1

            if normalized_tag is not None and normalized_tag in available_svm_normalized:
                for domain in expert_system.experts.keys():
                    if self.normalize_domain(domain) == normalized_tag:
                        relevant_svm.append(domain)
                        break

            if normalized_tag is not None and normalized_tag in available_bert_normalized:
                if bert_manager is not None:
                    for domain in bert_manager.get_available_domains():
                        if self.normalize_domain(domain) == normalized_tag:
                            relevant_bert.append(domain)
                            break
                elif bert_domains is not None:
                    for domain in bert_domains:
                        if self.normalize_domain(domain) == normalized_tag:
                            relevant_bert.append(domain)
                            break

            if normalized_tag is None or normalized_tag not in all_available:
                missing_domains.append(tag)

        # dict.fromkeys() deduplicates in O(N) while preserving insertion order
        relevant_svm = list(dict.fromkeys(relevant_svm))
        relevant_bert = list(dict.fromkeys(relevant_bert))

        result = {
            'relevant_svm_experts': relevant_svm,
            'relevant_bert_experts': relevant_bert,
            'missing_domains': missing_domains,
            'has_expert_coverage': len(relevant_svm) > 0 or len(relevant_bert) > 0,
            'available_svm': list(available_svm),
            'available_bert': list(available_bert),
            'input_tags': tags,
        }

        # ── graph_coverage_report event ───────────────────────────────────────
        # Internal event: reports routing coverage for developer tooling /
        # replay analysis.  visibility=internal keeps it out of the public SSE
        # stream.  Never blocks or modifies the returned result dict.
        self._emit(
            phase_name="graph_coverage_report",
            phase_id=3,
            substep="filter_experts",
            state="done",
            visibility="internal",
            message="Expert coverage resolved",
            detail=(
                f"svm={len(relevant_svm)} bert={len(relevant_bert)} "
                f"missing={len(missing_domains)}"
            ),
            metadata={
                "relevant_svm": relevant_svm,
                "relevant_bert": relevant_bert,
                "missing_domains": missing_domains,
                "has_expert_coverage": result["has_expert_coverage"],
                "input_tag_count": len(tags),
            },
        )

        return result

    def add_domain(self, domain_name, anchor_terms):
        """
        Dynamically add a new domain to the clustering system.
        """
        if not self.use_auto_clustering:
            print(f"\u26a0\ufe0f Cannot add domain dynamically - auto-clustering is disabled")
            return False

        self.clusterer.domain_anchors[domain_name] = anchor_terms
        self.clusterer._compute_domain_embeddings()
        self.clusterer.save_cache()
        # Invalidate normalize_domain LRU cache after adding a new domain (§3.1)
        self._normalize_domain_cached.cache_clear()

        print(f"\u2705 Added new domain: {domain_name} with {len(anchor_terms)} anchor terms")
        return True

    def analyze_coverage_gaps(self):
        """
        Analyze which domains have samples but no experts.
        """
        domains_with_samples = {d: count for d, count in self.coverage_stats.items() if count > 0}

        return {
            'total_domains_defined': len(self.domain_list),
            'domains_with_samples': len(domains_with_samples),
            'domain_sample_counts': domains_with_samples,
            'domains_needing_experts': [d for d in domains_with_samples.keys()]
        }

    def should_create_new_expert(self, filter_result):
        """
        Determine if new expert creation is needed.
        """
        return (
            len(filter_result['missing_domains']) > 0 and
            not filter_result['has_expert_coverage']
        )

    def get_coverage_report(self, registered_expert_domains=None):
        """
        Generate comprehensive coverage report.

        Args:
            registered_expert_domains: Optional set/list of domain names that
                have a live expert in the system.  When provided, the report
                classifies a domain as "supported" if and only if it appears
                in this collection.  Falls back to the original hard-coded
                allowlist only when the argument is omitted.
        """
        coverage_gaps = self.analyze_coverage_gaps()
        domains_with_samples = coverage_gaps['domain_sample_counts']

        if registered_expert_domains is not None:
            supported_set = {d.lower() for d in registered_expert_domains}
        else:
            supported_set = {'healthcare', 'medical', 'physics', 'chemistry'}

        supported_domains = {}
        unsupported_domains = {}

        for domain, count in domains_with_samples.items():
            if domain.lower() in supported_set:
                supported_domains[domain] = count
            else:
                unsupported_domains[domain] = count

        total_samples = sum(domains_with_samples.values())
        unsupported_samples = sum(unsupported_domains.values())

        return {
            'summary': {
                'total_domains_defined': coverage_gaps['total_domains_defined'],
                'domains_with_samples': coverage_gaps['domains_with_samples'],
                'supported_domains_count': len(supported_domains),
                'unsupported_domains_count': len(unsupported_domains),
                'total_samples_seen': total_samples,
                'samples_needing_new_experts': unsupported_samples,
                'coverage_percentage': (len(supported_domains) / len(domains_with_samples) * 100) if domains_with_samples else 0
            },
            'supported_domains': supported_domains,
            'unsupported_domains': unsupported_domains,
            'all_domains_with_samples': domains_with_samples
        }
